### ISSUE TITLE
[Suggestion] Option: visible tiles only

### ISSUE THREAD

**Issue by Adirelle** [gbl/Grid#10]
Hello,

Would it possible to add an option to display the lines only on visible tiles ? Viewing them on every tiles in range is sometimes quite annoying.

Best regards,
Adirelle.

**Comment by gbl** [comment]
Sorry, but I don't think I understand what you mean. Could you add a screenshot and highlight what the problem is?

**Comment by guillaume-perreal** [comment]
I meant that the grid was displayed on top of blocks that were out of sight. However, it seems the latest version has fixed it.

**Comment by Adirelle** [comment]
I meant Grid was drawing lines on top of blocks that were out of sight, like behind a wall or in an area full of stone. However, it seems the latest version has fixed this.
