### ISSUE TITLE
line issues

### ISSUE THREAD

**Issue by Martine1231** [gbl/Grid#11]
![2020-07-02_19 24 32](https://user-images.githubusercontent.com/67770237/86425536-4e211d80-bc9a-11ea-911d-1839d8ccbe11.png)
white lines running through everything, no color to boxes or spawn locations. Uninstalled and restarted, then reinstalled and the same results.

**Comment by Martine1231** [comment]
on fabric 1.16.1

**Comment by gbl** [comment]
That's not what it should look like. Are you using any other mods, especially ones that draw world overlays?

**Comment by Martine1231** [comment]
yes other mods, no to the overlays.
![Capture](https://user-images.githubusercontent.com/67770237/86504069-509e7880-bd69-11ea-94cc-2fe7d628c46e.PNG)

**Comment by Martine1231** [comment]
I went through and isolated fabritone as the conflict. without that, it works fine. sorry for not checking that beforehand.
