### ISSUE TITLE
[Suggestion] Option: Lock current overlay option

### ISSUE THREAD

**Issue by Martine1231** [gbl/Grid#12]
Trying to make a 128 circle(big circle in general) but when getting close to the edge on one side in particular the overlay cuts over to a different area. Would be cool to lock it in place while moving all around.

**Comment by gbl** [comment]
Use /grid distance to set the grid render distance to a value that's larger than the diameter. In the newest versions of Grid, this shouldn't be necessary as the distance is increased automatically with big values.

**Comment by Martine1231** [comment]
Awesome tried it out and looking good.
