### ISSUE TITLE
Control settings reset every time you launch the game

### ISSUE THREAD

**Issue by i0xHeX** [gbl/Grid#13]
**Description:**
Every time I launch the game, Grid controls are set by default.

**Reproduction:**
1. Remove all keys from Grid controls like that: (as what literally I do)
![Image](https://i.imgur.com/NJmXZOP.png)
2. Restart the game

**Info:**
Grid v1.16-fabric0.13.1-1.6
fabric-api-0.14.1+build.372-1.16

**Comment by gbl** [comment]
Fixed in version grid-1.16-fabric0.13.1-1.6-fixkeys.jar.
