### ISSUE TITLE
Mob spawns are shown between blocks when using Fabulous grapihcs

### ISSUE THREAD

**Issue by Rafii2198** [gbl/Grid#15]
Tile describes it entirely. This does not happen in Fast and Fancy settings only Fabulous. Tested on Minecraft version 1.16.1 with and without Sodium, same results.
Here is screenshot:
![image](https://user-images.githubusercontent.com/26695327/90432458-d896d280-e0ca-11ea-8bd4-74f13afaed53.png)

.

**Comment by gbl** [comment]
It's not just mob spawns, the problem happens with the rest of Grid's displays as well.

As OP said, it's only with Fabulous graphics.

And it doesn't happen if VoxelMap is loaded and has "display ingame waypoints" set to either signs, beacons, or both, even when no waypoints are defined.

I'm quite at a loss here; enabling depth test, depth mask, and setting depth func to LEQUAL doesn't help. It looks almost as if the world was drawn with depth mask = false in fabulous graphics, so, having no depth at all. Which sounds quite nonsensical.

**Comment by gbl** [comment]
And there's a similar / the same problem when the player isn't in first person mode (F5).

**Comment by Rafii2198** [comment]
OK so I just tested it in 1.16.2 and it is even worse - with Fabulous graphics grid and spawns doesn't render at all. I think maybe it is because they changed something in render in .2 release because of [MC-187411](https://bugs.mojang.com/browse/MC-187411) especially on Linux(which I am using now)

**Comment by Rafii2198** [comment]
I also asked friend if it is a case on Windows and he says that it he can't see them too

**Comment by gbl** [comment]
I just uploaded a beta version (Grid 1.6.2 for MC 1.16.2)  to CF that changes a lot about how I render the overlay. At least I wasn't able to make it bug out anymore. Could you please test that? Thanks.

**Comment by Rafii2198** [comment]
Ok so I tested in both 1.16.1 and .2 and it works perfectly!
I think it will work in .3 release as well as they didn't change anything with rendering

**Comment by gbl** [comment]
Solved on Fabric, currently unsolvable on Forge.
