### ISSUE TITLE
Broken grid blocks rendering (not a Fabritone problem this time apparently)

### ISSUE THREAD

**Issue by d-faure** [gbl/Grid#16]
The following two pictures are displaying the same place using a slightly changed view direction.

It has been tested using grid-1.16.2-fabric0.17.2-1.6.jar on a relevant game instance and loader on all the graphic modes (from fast to fabulous) and the Java runtime is v1.8.0_251

![2020-08-20_15 20 18](https://user-images.githubusercontent.com/1654767/90775790-8ab3e180-e2f9-11ea-8472-9379e70eba5b.jpg)

Whereas the grid blocks are rendered as requested in the first screenshot above (a 5x5 grid of blue squares), as soon as you are looking downward, the rendering is unexpectedly drawn in white with interfering lines as you may see in the second screenshot.

![2020-08-20_15 20 33](https://user-images.githubusercontent.com/1654767/90775982-cd75b980-e2f9-11ea-808b-c4af93a6ab35.jpg)

**Comment by gbl** [comment]
Disable Fabritone and Grid will work as it should.

**Comment by d-faure** [comment]
Please tell me how could I do that?
My other mods are:
  [✔️] beenfo-1.16.2-fabric0.17.2-1.1.1
  [✔️] blockmeter-1.16.2-fabric0.17.2-1.5.1
  [✔️] collective-1.16.2-1.38
  [✔️] easyelytrato_1.16.2-1.5
  [✔️] fabric-api-0.18.0+build.397-1.16
  [✔️] fabricmod_VoxelMap-1.10.10_for_1.16.2
  [✔️] grid-1.16.2-fabric0.17.2-1.6
  [✔️] modmenu-1.14.6+build.31
  [✔️] orderly-2.0.0-alpha.10-1.16
  [✔️] shulkerboxtooltip-2.1.1+1.16.2
  [✔️] Unsuspicious-Stew-0.1-Fabric-1.16.2
  [✔️] worldtime-1.16.2-fabric0.17.2-1.2.4

**Comment by gbl** [comment]
Oh. Seems I answered too quickly. There is a mod called Fabritone that causes the excact display problems that you're describing, so I thought you had that. Seems to be another mod in that list.

**Comment by gbl** [comment]
Does that easyelytrato even work for you? It seems to a Forge mod to me (and also collective, which is just a library for easyelytrato).

**Comment by d-faure** [comment]
I found easylytrato useful few months ago as I wasn't skilled at elytra on a previous version, but it seems that I can manage without it now, so 2 mods to remove (good!).
Trying different mod activation/configuration, I found that VoxelMap was the offending one.

**Comment by gbl** [comment]
Oh wait. So this problem does happen with VoxelMap and doesn't happen without it? Thanks, that'll hopefully help me find the problem.

**Comment by d-faure** [comment]
Exactly.

For the record, I looked for an alternative map+waypoint handler, and found that Xaeros stuff (mini+world map) seemed to work without issue with Grid.

**Comment by gbl** [comment]
This is strange, because I'm trying with VoxelMap right now, and don't seem to have any problem. This is with some other mods you don't have, and you have some mods that I don't have, so I'm trying to recreate a MC instance that has exactly the same setup as yours. Can you post a complete log file (with Voxelmap, that has the problem) to pastebin or something and link it here?

**Comment by d-faure** [comment]
Here's 1 day expiry pastebin of a buggy execution trace: https://pastebin.com/6sZJkCjY

**Comment by gbl** [comment]
Thanks for the paste. I'm sorry, but I'm giving up on this for now; I recreated the exact mod list you're using (including beem and Autofish for example), and the bug just doesn't happen to me.

On a side node, as I see you're using several of my mods, and you seem to be speaking French from your paste, I'd be happy if someone helped me with french translations of my mods at https://crowdin.com/profile/gbl :)

**Comment by d-faure** [comment]
Unchecked mods are disabled (not loaded). VoxelMap has cached data and stored waypoints on the displayed area.

I gave translations to most of your mods I used (even if now some of them aren't relevant).

**Comment by gbl** [comment]
Here's an example of what it looks like for me - two BlockMeter boxes, a Beem beam, two VoxelMap beacons, and Grid blocks. Sorry, I just can't reproduce your bug.
![Screenshot_2020-08-21_13-38-48](https://user-images.githubusercontent.com/243563/90887129-18ec9e00-e3b4-11ea-9ae7-5568be79b206.png)

Thank you for the translations, they'll be in my next mod versions!

This is with:
```
Mods:
  [✔️] Autofish-0.9.0-fabric-mc1.16.2
  [✔️] beem-1.3.2
  [✔️] beenfo-1.16.2-fabric0.17.2-1.1.1
  [✔️] blockmeter-1.16.2-fabric0.17.2-1.5.1
  [✔️] fabric-api-0.18.0+build.397-1.16
  [✔️] fabricmod_VoxelMap-1.10.10_for_1.16.2
  [✔️] grid-1.16.2-fabric0.17.2-1.6
  [✔️] modmenu-1.14.6+build.31
  [✔️] orderly-2.0.0-alpha.10-1.16
  [✔️] shulkerboxtooltip-2.1.1+1.16.2
  [✔️] Unsuspicious-Stew-0.1-Fabric-1.16.2
  [❌] worldtime-1.16.2-fabric0.17.2-1.2.4.jar (disabled)
```

**Comment by d-faure** [comment]
Have you tried rendering the VoxelMap waypoints in beacon-only mode?
This is my usual configuration, and hence, the one which trigger the drawing bug!

**Comment by gbl** [comment]
Wow, that does it!
Sings, both, and off don't cause the problem, but beacons-only does. Now at least I can test it.

**Comment by gbl** [comment]
Found it and fixed it! VoxelMap, in waypoints-are-beacons mode, changes a GL setting, which it does reset when drawing signs, but leaves changed otherwise. Now I explicitly change that setting back before drawing Grid. Just uploaded new versions for 1.16.1 and 1.16.2, which already contain your french translations!

**Comment by d-faure** [comment]
Nice! And incidentally, this should also work with Fabritone!
