### ISSUE TITLE
Command autocomplete doesn't work (1.16.2 Forge)

### ISSUE THREAD

**Issue by Ludi87** [gbl/Grid#17]
Minecraft: 1.16.2
Forge: 33.0.61
Grid: grid-1.16.2-forge33.0.5-1.6.1

Typing out a command I'm getting the error "Unknown or incomplete command" - but if I press enter, the command still works.

![2020-09-13_12 55 29](https://user-images.githubusercontent.com/13112051/93016353-d8520000-f5c0-11ea-9770-151617403d49.png)

**Comment by gbl** [comment]
Yes, that's right. Can't help that on Forge, because Forge stopped having a client command API after 1.12.

**Comment by gbl** [comment]
See also here: https://forums.minecraftforge.net/topic/89495-client-side-commands-in-116/ - As long as Forge doesn't solve that, I can't do anything about the missing autocompletion.
