### ISSUE TITLE
[Feature Request] A sphere viewer

### ISSUE THREAD

**Issue by SekoiaTree** [gbl/Grid#20]
There's a circle viewer, why not a sphere one? I tried coding it myself but the code was a bit too confusing for me (I hate rendering...)

**Comment by gbl** [comment]
Rendering spheres, or actually anything that isn't 2-dimensional, doesn't really work well with just lines - the "what's where" is way too confusing. Ever tried building in litematica without setting the render mode to "current layer only" or maybe "all below" ?

That said - as you said "tried coding it myself" and "hate rendering" - why don't you leave the rendering to litematica and just create a .litematic file that has a sphere of blocks? You're welcome to use the "how do I write a .litematic file" part from my Grabcraft-Litematic mod here: https://github.com/gbl/GrabcraftLitematic/blob/master/src/main/java/de/guntram/mcmod/GrabcraftLitematic/Litematic.java.

I might even give that a shot myself at some point....

**Comment by SekoiaTree** [comment]
Fair enough!

**Comment by PhoenixIV** [comment]
I am also looking for this. I found https://www.curseforge.com/minecraft/mc-mods/minihud/screenshots if you wish for inspiration.
