### ISSUE TITLE
[Forge] Divide by 0 crash

### ISSUE THREAD

**Issue by Trnrr** [gbl/Grid#21]
You can move the Z & X distance to 0. Doing so will crash your game if you have the grid enabled. If you set it to 0 and then enable the grid it will also crash.

https://gist.github.com/Trnrr/1a2623eeeb9888bfa3764a08f79607b8

Using:
grid-1.16.4-forge35.0.7-1.6.1.jar
forge-1.16.4-35.1.13-client.jar

**Comment by gbl** [comment]
Thanks for reporting this. Just uploaded grid-1.16.4-forge35.0.7-1.6.4.jar which fixes this (min slider position is now 1, not 0)
