### ISSUE TITLE
1.18 outdated spawn light levels

### ISSUE THREAD

**Issue by ghost** [gbl/Grid#30]
minecraft: 1.18 rc3
fabric loader: 0.12.5-1.18-rc3
fabric-api: 0.43.1+1.18
grid: 1.18-pre5-fabric0.42.8-1.66

/grid spawns is showing block light levels <8 as spawnable in 1.18. I believe they've changed it so that hostile mobs will only spawn at light level 0 in 1.18.

edit: I'd been using it via hotkey so I'd only just noticed that /grid spawns accepts an argument for the light level but changing the value doesn't seem to do anything.

**Comment by ghost** [comment]
`/grid spawns 1` works.

**Comment by gbl** [comment]
The 1.18 version has /grid spawns 1 as its default, and also fixes a bug that prevented biome and light level display below y=0.
