### ISSUE TITLE
Mod crashes in 1.19.4 when trying to open the UI menu

### ISSUE THREAD

**Issue by guspolly** [gbl/Grid#36]
I have grid-1.19.3-fabric0.68.1-1.6.7 with Fabric 0.14.18 in Minecraft 1.19.4. I'm able to start the game and load a world, and I can use the mod's functions with commands, but when I try to open the mod's menu with the keybind, the game crashes. I usually use other mods, but I temporarily ran in with just Fabric and Grid to see if there was a conflict, and it still crashed.

[crash-2023-03-26_20.07.48-client.txt](https://github.com/gbl/Grid/files/11073461/crash-2023-03-26_20.07.48-client.txt)

**Comment by srnyx** [comment]
Happening to me too;
**Minecraft:** 1.19.4
**Loader:** Fabric 0.14.19
**Grid:** 1.19.3-fabric0.68.1-1.6.7

**Comment by gbl** [comment]
yes, 1.19.3 screens don't work in 1.19.4. There's a 1.20 version now that has a working config again.
