### ISSUE TITLE
grid-1.20-fabric0.83.0-1.6.8 crash on load

### ISSUE THREAD

**Issue by blockbandit** [gbl/Grid#41]
openjdk 17.0.8
grid-1.20-fabric0.83.0-1.6.8
fabric-loader 0.14.22
fabric-api 0.86.1
Minecraft 1.20.1

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'grid'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) <snip>
[crash-2023-08-07_19.49.00-client.txt](https://github.com/gbl/Grid/files/12282423/crash-2023-08-07_19.49.00-client.txt)

Full crash log attached

**Comment by gbl** [comment]
Please try installing cloth config. It should be a dependency but *something* went wrong with them.

**Comment by blockbandit** [comment]
Hi gbl. Installing Cloth Config v11.1.106 resolves the issue. Grid now loads successfully. Thank you :)
