### ISSUE TITLE
Grid rendering artifacts at large distances

### ISSUE THREAD

**Issue by blockbandit** [gbl/Grid#42]
openjdk 17.0.8
grid-1.20-fabric0.83.0-1.6.8
fabric-loader 0.14.22
fabric-api 0.86.1
cloth-config 11.1.106
Minecraft 1.20.1

I could not get grid to display properly server that I play on and I am at 20,000,000 blocks out.  Testing reveals that rendering artifacts start happening at around 1 million blocks from 0,0. The artifacts get worse with distance.

How to reproduce:
Create a new world
TP self to distances of large magnitude in the millions of blocks to observe how rendering gets more and more broken, whether its blocks, lines, circles or biome

**Comment by gbl** [comment]
Can confirm this happens in a single player world, but I don't know the reason yet. Might have to do with coordinates being calculated as floats, not doubles. But the maximum float that can be represented exactly is 16,777,217, and the problem starts at 1,000,000, so not sure about that.

**Comment by gbl** [comment]
And it's not that easy to use doubles as the MC graphics primitives like `Matrix3f` and `Matrix3f` use floats as well.

**Comment by gbl** [comment]
Fixed in 1.7 (done on Modrinth, still updating on Curseforge)
