### ISSUE TITLE
Client Commands dependency not declared

### ISSUE THREAD

**Issue by LemmaEOF** [gbl/Grid#5]
The fabric.mod.json doesn't declare a dependency on Client Commands so if the mod is loaded without client commands present, it will crash from a NoClassDefFoundError instead of Fabric noting the dependency.

**Comment by gbl** [comment]
Grid normally comes with a JIJ'ed version of CCC so that isn't an issue. There was one version of Grid that did NOT come with CCC to fix api differences between  CCC 2.x and 3.x , but all of that is long gone now.
