### ISSUE TITLE
Issues with grid moving

### ISSUE THREAD

**Issue by ennything** [gbl/Grid#6]
Trying to do a perimeter for my witch farm and it keeps moving so i cant make it

**Comment by gbl** [comment]
Are you sure you've used /grid circles to do the perimeter? They should not move. What does move is the light level overlay, when it's enabled.
Or maybe you have /grid here bound to some key that you keep using? /grid here is more or less the only way to make the grid move.

**Comment by SanjivanM** [comment]
I have the same issue, if you're making large circles (radius of 23 blocks, for example) and you get close to the edge of the circle you're working on, the outline jumps to another circle, making it impossible to complete the one you are working on.

**Comment by gbl** [comment]
Use /grid distance to set the render distance to a higher value than the diameter, this should fix it.
