### ISSUE TITLE
[1.14-fabric0.2.7-1.4] - Showing spawn locations drastically, reduces FPS

### ISSUE THREAD

**Issue by spradlin-dev** [gbl/Grid#8]
Mod Version: 1.14-fabric0.2.7-1.4
Fabric API: v0.4.0+build.240-1.14
Client Commands: v0.2.1+1.14-pre5
Cloth Config: v0.2.1+build.14

Showing mob spawn locations drops FPS from 60 to 30.  Turning it back off restores FPS.

This is not a new issue, I just figured I'd finally report it.

**Comment by SanjivanM** [comment]
That's due to all the calculations the mod does, as well as rendering the low light locations.

**Comment by gbl** [comment]
What SanjivanM says. I'm using a Minecraft API - `SpawnHelper.canSpawn` - to check if a mob can spawn at a position, and according to the profiler, 95% of the CPU time is spent in that method.
